twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        macarte_server: '%env(MACARTE_SERVER)%'
        edugeo_server: '%env(EDUGEO_SERVER)%'
        lumni_cas: '%env(LUMNI_CAS)%'
        piwik_id: '%env(PIWIK_ID)%'

when@test:
    twig:
        strict_variables: true
